<![CDATA[name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Hamoex
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=green&color_dots=#0d1117,#00F548,#00C853,#00E676,#69F0AE,#B9F6CA

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
]]>